name: Check Build

on: 
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'

jobs:
  test:
    name: Test - Build & Unit
    #no integration tests so far
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup - Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      - name: Setup - Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-:  

      - name: Build - Maven Package
        run: mvn -B clean package -DskipTests

      - name: Test - Maven Verify
        run: mvn -B clean verify
