name: Develop PR CI

on: 
  pull_request:
    branches: 
      - 'develop'

jobs:
  test:
    name: Test - Build & Unit
    #no integration tests so far
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
    - name: Build - Maven Package
      run: mvn -B clean package -DskipTests
    - name: Test - Maven Verify
      run: mvn -B clean verify
