name: Develop CI

on: 
  push:
    branches: 
      - 'develop'

jobs:
  test:
    name: Test - Build & Unit
    #no integration tests so far
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup - Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Setup - Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-:  
      - name: Build - Maven Package
        run: mvn -B clean package -DskipTests
      - name: Test - Maven Verify
        run: mvn -B clean verify
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup - Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Restore - Maven Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-:  
      - name: Analyze - SonarCloud Scan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  license-to-pages:
    name: Publish licenses to pages
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup - Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Restore - Maven Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-:  
      - name: Build dependencies/licenses files
        run: mvn project-info-reports:dependencies
      - name: Upload licenses - Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dependencies-licenses
          path: target/site
      - name: Generate docs/dependencies dir
        run: mkdir docs/dependencies
      - name: Move built files into docs/dependencies
        run: mv target/site docs/dependencies
      - name: Copy Readme into docs
        run: cp README.md docs/README.md
      - name: Cleanup
        run: mvn clean
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
