name: GH-Pages CI

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  publish-pages:
    name: Publish dependencies and licenses to github pages
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup - Java
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.x
          distribution: 'adopt'

      - name: Restore - Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-:  

      - name: Build dependencies/licenses files
        run: mvn -B project-info-reports:dependencies

      - name: Upload licenses - Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependencies-licenses
          path: target/site

      - name: Generate docs/dependencies dir
        run: mkdir -p docs/dependencies

      - name: Move built files into docs/dependencies
        run: mv target/site/* docs/dependencies

      - name: Rename dependencies.html to index.html
        working-directory: docs/dependencies
        run: mv dependencies.html index.html

      - name: Copy Readme into docs (as index.md)
        run: cp README.md docs/index.md

      - name: Configure Pages
        working-directory: docs
        run: |-
          echo "theme: jekyll-theme-midnight" > _config.yml

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true
