name: Sonar CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
    paths-ignore: 
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup - Java
      uses: actions/setup-java@v4
      with:
        java-version: 11.0.x
        distribution: 'adopt'

    - name: Setup - Fetch complete history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Restore - Maven Cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-:  

    - name: Analyze - SonarCloud Scan
      run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
